Adds governance documents
numfocus/DISCOVER-Cookbook pull request #82
Opened 2024-12-26 14:46 UTC by aterrel

This PR adds some baseline governance docs. 

- GOVERNANCE.md for addressing purpose, roles, responsibilities, and
  conflict resolution
- CONTRIBUTING.md for describing the appropriate contributions to the
  repository

See issue #75 for context

2025-01-11 14:05 UTC, aterrel commented
@kamila-NF / @melissawm  can you add any notes from your discussion at the @numfocus/disc-committee meeting?

2025-01-11 14:13 UTC, tkoyama010 requested changes

2025-01-11 14:13 UTC, tkoyama010 commented on GOVERNANCE.md
> +
```suggestion

```

2025-01-11 14:13 UTC, tkoyama010 commented on GOVERNANCE.md
> +# **Open Source Project � Objectives**
```suggestion
# **Open Source Project Objectives**
```

2025-01-26 14:48 UTC, aterrel commented
I'm going to go ahead and commit this because I get numerous requests each week and I want to help route them better. We can review the issue in the DISC meeting and retroactively update it.

2025-01-26 14:50 UTC, merged